â €â €â € < A little about her >

Full Name: LiÃ¡n MiÃ¡nhuÄ
Hanzi: è¿æ£‰èŠ±
Birthday: Beijing, 28 April 2007
Face Claim: (G)-IDLE Shuhua

â €â €â € < ğ—•ğ—®ğ—°ğ—¸ğ—´ğ—¿ğ—¼ğ˜‚ğ—»ğ—± ğ—¦ğ˜ğ—¼ğ—¿ğ˜† >

When she was young, she dreamt of being a famous singer and she decided to join Eunnoo School of Arts at all costs.

Of course, both her parents do what they do best: ensure their childâ€™s wish come true with the resources they have.

Mianhua begitu sering mengatakan cita-citanya adalah menjadi penyanyi, sampai seluruh kenalan sudah tahu akan hal itu.

Keluarganya kerap menyinggung soal bahwa â€œXiÃ o HuÄ adalah penyanyi kita!â€ dan memang benar adanya.
_____________________________________________________
Xiao Hua (xiÃ o huÄ) or æ ¡èŠ± means little flower.

Sang ayah, MÃ¹chÃ©n (æ²è¾°) sampai-sampai sudah lelah mendengar anak perempuannya bernyanyi dan bermain piano sampai larut malam.

Ketika MiÃ¡nhuÄ menguasai gitar akustik, anak perempuan LiÃ¡n itu semakin menjadi. Berjam-jam dihabiskan untuk menulis lagu.

Pada akhirnya, setelah MÃ¹chÃ©n dan ZÇhÃ¡n memberikan persetujuan soal edukasi anak termuda mereka, MiÃ¡nhuÄ diputuskan akan pergi ke Eunnoo School of Arts.

â€œJika putriku akan menjadi artis, maka ia perlu mendapatkan pendidikan yang terbaik untuk dapat menjadi yang terbaik.â€

Perbedaan usia antara MÃ¹yÃ¡ng dan MiÃ¡nhuÄ memang terasa jauh, namun tetap saja, sang kakak menyayangi adik satu-satunya itu.

Berbagai pesan juga peringatan diberikan, hingga ke detik terakhir sebelum mereka berpisah.

Karena MÃ¹yÃ¡ng memiliki pekerjaan di luar kota, mereka hanya dapat bertemu saat acara keluarga terakhir yang sekaligus dijadikan pesta perpisahan.

ZÇhÃ¡n mengucapkan beberapa patah kata soal bahwa kedua putrinya sekarang akan jauh darinya.

â€œEunnoo, ya?â€ Ujar MÃ¹chÃ©n, disambut anggukan bersemangat dari MiÃ¡nhuÄ yang sampai menampilkan presentasi agar kedua orang tuanya setuju.

ZÇhÃ¡n terdiam, ekspresi wajahnya kaku. Sang ibu memang lebih banyak menyuarakan rasionalitas, namun juga berat hati karena terbiasa dekat dengan sang anak.

â€œSepertinya ayah kenal salah seorang alumnus dari sekolah itu. Biar ayah hubungi, siapa tahu beliau masih memiliki kenalan dari sana.â€

MiÃ¡nhuÄ sekonyong-konyong memberikan pelukan kepada sang ayah, yang tersenyum juga melingkarkan lengan di pundak anaknya.

Ada banyak hal yang MÃ¹chÃ©n mampu lakukan. Setelah begitu sukses di berbagai bidang bisnis, terlebih tanah dan lingkungannya, edukasi anak-anaknya selalu dijadikan prioritas.

â €â €â € < ğ—£ğ—¹ğ—¼ğ˜ ğ—§ğ˜„ğ—¶ğ˜€ğ˜ >

It is not always easy for Mianhua to get through the ups and downs of high school. She likes to think she can do it all and that is how she projects herself.

However, she still has her insecurities and would often cry behind closed doors, allowing no one to know.

Walaupun MiÃ¡nhuÄ memiliki kecintaan besar terhadap menyanyi, tetap tidak selalu mudah baginya untuk bersaing dengan terbaik dari terbaik.

Teori musik berarti ia tidak hanya harus menguasai praktik, namun juga teori. Oleh karena itu, terkadang nona LiÃ¡n harus menghabiskan larut malam di meja belajar.

Kuis mandiri dilakukan, semua demi mempertahankan tempat yang telah didapatkan.

Karena yang tersulit bukanlah menang, namun mempertahankan posisi yang sudah sedemikian rumit untuk digapai.

â €â €â € < ğ—£ğ—²ğ—¿ğ˜€ğ—¼ğ—»ğ—®ğ—¹ğ—¶ğ˜ğ˜† >

Pantang menyerah, sejak kecil sudah mengetahui apa yang ingin dilakukan dan tidak goyah.

Jika di rumah, tepatnya di Beijing bersama keluarganya, MiÃ¡nhuÄ tergolong pendiam. Hanya ketika bernyanyi saja gadis itu seolah keluar dari cangkangnya.

Walaupun MiÃ¡nhuÄ tergolong pandai, namun tak jarang anak kedua keluarga LiÃ¡n kerap pelupa.

â €â €â € < ğ—§ğ—¿ğ—¶ğ˜ƒğ—¶ğ—® >

1. She learned to dance traditional Chinese dancing so she was a performer of traditional Chinese dance.
2. She prefers the egg whites, and pours the cereal before the milk. Loves orange over lemon.
